<a href="https://colab.research.google.com/github/CaroBrambila/Actividad-2.1-2.2-y-2.3-Reto-1/blob/main/2_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
#Carga desde un archivo .csv sin indice
df = pd.read_csv('inmuebles2.csv')
df

,Unnamed: 0,Esta es una base de datos que describe las operaciones inmobiliarias de una empresa,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8
0,0,Referencia,Fecha Alta,Tipo,Operación,Provincia,Superficie,Precio Venta,Fecha Venta,Vendedor
1,1,1,2004-01-01 00:00:00,Parking,Alquiler,Lleida,291,2133903,2004-06-19 00:00:00,Carmen
2,2,2,2004-01-01 00:00:00,Local,Venta,Girona,185,1945424,2004-04-19 00:00:00,Pedro
3,3,3,2004-01-01 00:00:00,Oficina,Alquiler,Girona,82,NaN,2004-11-08 00:00:00,Joaquín
4,4,4,2004-01-02 00:00:00,Parking,Alquiler,Girona,285,NaN,2004-04-27 00:00:00,Jesús
...,...,...,...,...,...,...,...,...,...,...
3333,3333,3333,2007-04-29 00:00:00,Industrial,Alquiler,Lleida,221,1450644,NaN,NaN
3334,3334,3334,2007-04-29 00:00:00,Piso,Alquiler,Girona,55,454080,NaN,NaN
3335,3335,3335,2007-04-30 00:00:00,Suelo,Venta,Tarragona,78,740688,NaN,NaN
3336,3336,3336,2007-04-30 00:00:00,Piso,Alquiler,Barcelona,88,397408,NaN,NaN
3337,3337,3337,2007-04-30 00:00:00,Parking,Venta,Lleida,NaN,2140712,NaN,NaN

In [3]:
#Eliminar primera fila o filas innecesarias
df1= pd.read_csv('inmuebles2.csv', skiprows=1)
df1

,0,Referencia,Fecha Alta,Tipo,Operación,Provincia,Superficie,Precio Venta,Fecha Venta,Vendedor
0,1,1,2004-01-01 00:00:00,Parking,Alquiler,Lleida,291.0,2133903.0,2004-06-19 00:00:00,Carmen
1,2,2,2004-01-01 00:00:00,Local,Venta,Girona,185.0,1945424.0,2004-04-19 00:00:00,Pedro
2,3,3,2004-01-01 00:00:00,Oficina,Alquiler,Girona,82.0,NaN,2004-11-08 00:00:00,Joaquín
3,4,4,2004-01-02 00:00:00,Parking,Alquiler,Girona,285.0,NaN,2004-04-27 00:00:00,Jesús
4,5,5,2004-01-02 00:00:00,Suelo,Venta,Tarragona,152.0,185000.0,2004-07-10 00:00:00,María
...,...,...,...,...,...,...,...,...,...,...
3332,3333,3333,2007-04-29 00:00:00,Industrial,Alquiler,Lleida,221.0,1450644.0,NaN,NaN
3333,3334,3334,2007-04-29 00:00:00,Piso,Alquiler,Girona,55.0,454080.0,NaN,NaN
3334,3335,3335,2007-04-30 00:00:00,Suelo,Venta,Tarragona,78.0,740688.0,NaN,NaN
3335,3336,3336,2007-04-30 00:00:00,Piso,Alquiler,Barcelona,88.0,397408.0,NaN,NaN
3336,3337,3337,2007-04-30 00:00:00,Parking,Venta,Lleida,NaN,2140712.0,NaN,NaN

In [4]:
#Eliminar columnas innecesarias
#axis = 1 para columnas
#axis = 0 para filas
df2= df1.drop(['0','Referencia'], axis=1)
df2

,Fecha Alta,Tipo,Operación,Provincia,Superficie,Precio Venta,Fecha Venta,Vendedor
0,2004-01-01 00:00:00,Parking,Alquiler,Lleida,291.0,2133903.0,2004-06-19 00:00:00,Carmen
1,2004-01-01 00:00:00,Local,Venta,Girona,185.0,1945424.0,2004-04-19 00:00:00,Pedro
2,2004-01-01 00:00:00,Oficina,Alquiler,Girona,82.0,NaN,2004-11-08 00:00:00,Joaquín
3,2004-01-02 00:00:00,Parking,Alquiler,Girona,285.0,NaN,2004-04-27 00:00:00,Jesús
4,2004-01-02 00:00:00,Suelo,Venta,Tarragona,152.0,185000.0,2004-07-10 00:00:00,María
...,...,...,...,...,...,...,...,...
3332,2007-04-29 00:00:00,Industrial,Alquiler,Lleida,221.0,1450644.0,NaN,NaN
3333,2007-04-29 00:00:00,Piso,Alquiler,Girona,55.0,454080.0,NaN,NaN
3334,2007-04-30 00:00:00,Suelo,Venta,Tarragona,78.0,740688.0,NaN,NaN
3335,2007-04-30 00:00:00,Piso,Alquiler,Barcelona,88.0,397408.0,NaN,NaN
3336,2007-04-30 00:00:00,Parking,Venta,Lleida,NaN,2140712.0,NaN,NaN

In [5]:
#Registros fecha alta
filtro1=df2[(df2["Fecha Alta"]=="2007-04-29 00:00:00") & (df2["Fecha Alta"]=="2004-01-02 00:00:00")]
filtro1

Empty DataFrame
Columns: [Fecha Alta, Tipo, Operación, Provincia, Superficie, Precio Venta, Fecha Venta, Vendedor]
Index: []

In [6]:
#Convertir archivo filtrado a CSV
filtro1.to_csv("filtro1.csv")

In [7]:
filtro2 = df2[(df2["Tipo"]=="Parking") | (df2["Tipo"]=="Local") | (df2["Tipo"]=="Industrial") | (df2["Tipo"]=="Piso")]
filtro2

,Fecha Alta,Tipo,Operación,Provincia,Superficie,Precio Venta,Fecha Venta,Vendedor
0,2004-01-01 00:00:00,Parking,Alquiler,Lleida,291.0,2133903.0,2004-06-19 00:00:00,Carmen
1,2004-01-01 00:00:00,Local,Venta,Girona,185.0,1945424.0,2004-04-19 00:00:00,Pedro
3,2004-01-02 00:00:00,Parking,Alquiler,Girona,285.0,NaN,2004-04-27 00:00:00,Jesús
5,2004-01-03 00:00:00,Industrial,Alquiler,Girona,131.0,953156.0,2004-09-05 00:00:00,Pedro
8,2004-01-04 00:00:00,Piso,Alquiler,Lleida,108.0,1024380.0,2004-12-28 00:00:00,Jesús
...,...,...,...,...,...,...,...,...
3330,2007-04-27 00:00:00,Local,Venta,Girona,110.0,845790.0,NaN,NaN
3332,2007-04-29 00:00:00,Industrial,Alquiler,Lleida,221.0,1450644.0,NaN,NaN
3333,2007-04-29 00:00:00,Piso,Alquiler,Girona,55.0,454080.0,NaN,NaN
3335,2007-04-30 00:00:00,Piso,Alquiler,Barcelona,88.0,397408.0,NaN,NaN
3336,2007-04-30 00:00:00,Parking,Venta,Lleida,NaN,2140712.0,NaN,NaN

In [8]:
filtro2.to_csv("filtro2.csv")

In [9]:
#Filtro3. registros con “Provincia” igual a “Girona” y con “Superficie” mayor a “100”
filtro3= df2[(df2["Provincia"]=="Giona") & (df2["Superficie"]> 100)]
filtro3

Empty DataFrame
Columns: [Fecha Alta, Tipo, Operación, Provincia, Superficie, Precio Venta, Fecha Venta, Vendedor]
Index: []

In [10]:
filtro3.to_csv("filtro3.csv")

In [11]:
# Filtro4. registros con “Precio Venta: mayor a 1000,000” o “vendedor” igual a “Carmen o Joaquin”
filtro4= df2[(df2["Precio Venta"]>1000000) | (df2["Vendedor"]=="Carmen") | (df2["Vendedor"]=="Joaquin") ]
filtro4

,Fecha Alta,Tipo,Operación,Provincia,Superficie,Precio Venta,Fecha Venta,Vendedor
0,2004-01-01 00:00:00,Parking,Alquiler,Lleida,291.0,2133903.0,2004-06-19 00:00:00,Carmen
1,2004-01-01 00:00:00,Local,Venta,Girona,185.0,1945424.0,2004-04-19 00:00:00,Pedro
7,2004-01-03 00:00:00,Oficina,Venta,Girona,235.0,2158475.0,2004-10-31 00:00:00,Jesús
8,2004-01-04 00:00:00,Piso,Alquiler,Lleida,108.0,1024380.0,2004-12-28 00:00:00,Jesús
9,2004-01-04 00:00:00,Parking,Venta,Lleida,299.0,2042768.0,2004-10-06 00:00:00,Joaquín
...,...,...,...,...,...,...,...,...
3325,2007-04-25 00:00:00,Industrial,Alquiler,NaN,296.0,2078216.0,NaN,NaN
3328,2007-04-26 00:00:00,Piso,Venta,Barcelona,264.0,2517504.0,NaN,NaN
3331,2007-04-29 00:00:00,Oficina,Venta,Lleida,190.0,1031320.0,NaN,NaN
3332,2007-04-29 00:00:00,Industrial,Alquiler,Lleida,221.0,1450644.0,NaN,NaN
3336,2007-04-30 00:00:00,Parking,Venta,Lleida,NaN,2140712.0,NaN,NaN

In [12]:
filtro4.to_csv("filtro4.csv")

In [14]:
# Filtro5. registros que no sean de “Provincia : Barcelona“
filtro5= df2[~(df2["Provincia"]=="Barcelona")]
filtro5
filtro5.to_csv("filtro5.csv")

In [16]:
#Filtro6. registros que no sean de “Operación: alquiler “ ni “Tipo: oficina“
filtro6=df2[(df2["Operación"]=="Alquiler") &(df2["Tipo"]=="Oficina")]
filtro6
filtro6.to_csv("filtro6.csv")